# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5e2e7a38a69606c404a553c4322b7600f6de9f450150c95ced872be92b863dcbfbf24c9a9afb4a77a0ebe9cdb0de0f8c09fdd8d3071e1ee678f6040c4dc1661
  mail_gun_api_key: <%= ENV["MAILGUN_API_KEY"] %>
  mailgun_domain: <%= ENV["MAILGUN_DOMAIN"] %>
test:
  secret_key_base: aaa42abbe7bf80b449e0e8a8fa95853317ad91a3c49ca46d33ca134d146a59dd45dbd6b03fe88d6fd531f4f2ff27a32ebb91bf00ea9f74a8c535d796ff4354fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
